version: '3.4'

services:
  userdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  swiftusermanagement.api:
    image: ${DOCKER_REGISTRY-}swiftusermanagementapi
    build:
      context: .
      dockerfile: SwiftUserManagement.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: